artifacts_root : artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/pratyuds/Text-Summarizer-project/raw/main/raw_data/summarizer-data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion